name: Create New Page

on:
  workflow_dispatch:
    inputs:
      loc:
        description: 'location'
        default: '/content/'
        required: true
      name:
        description: 'file title'
        default: '.md'
        required: true

# Sets permissions of the GITHUB_TOKEN to allow commits
permissions:
  contents: write
  id-token: write

# Allow only one concurrent creation, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these draft deployments to complete.
concurrency:
  group: "creation"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  create:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.147.9
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Create file
        run: |
          hugo new \
            --config "${{ inputs.loc + inputs.name }}"
